services:
  - type: web
    name: steam-page-optimizer
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: steam-page-optimizer-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: steam-page-optimizer-db
    databaseName: steam_page_optimizer
    user: steam_page_optimizer 